### PR TITLE
Simplify travis.yml

### PR DESCRIPTION
**Pull request by lowks**
Simplify travis.yml

### CODE REVIEW

**Comment by parroty** [comment]
Thanks! 
The first travis build was failing, but succeeded with the retry. Not quite sure about the reason though.

**Comment by lowks** [comment]
Kiex is unstable on Travis

**Comment by parroty** [comment]
OK, will be monitoring for a while. It's good to have native elixir at Travis anyway.

**Comment by lowks** [comment]
If you encounter problems please file a report to them so that they can
they can improve  their Elixir setup. The problem seems more pronounced
when you have rapid fire commits though.


[image: Low Kian Seong on about.me]

Low Kian Seong
about.me/lowkianseong
    <http://about.me/lowkianseong>

**Comment by parroty** [comment]
I will do so when I could reproduce the error.

**Pull request merged**
